// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd2IHiApw7vrf5cIcJyqYQeWtmuQaH2p4',
    appId: '1:379694767475:web:bfdb6b471fc30f0fdd3906',
    messagingSenderId: '379694767475',
    projectId: 'ichibanauto-2f872',
    authDomain: 'ichibanauto-2f872.firebaseapp.com',
    storageBucket: 'ichibanauto-2f872.appspot.com',
    measurementId: 'G-1S4G7HK2SZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABILQ98axUAtfz3Ou0HAWcne8C1eeOYk8',
    appId: '1:379694767475:android:92b51a0886160c57dd3906',
    messagingSenderId: '379694767475',
    projectId: 'ichibanauto-2f872',
    storageBucket: 'ichibanauto-2f872.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDB5d_6-VTmBPMlqeneO_wSBbp-GW4s0Eg',
    appId: '1:379694767475:ios:d7e7f4774b8e7be6dd3906',
    messagingSenderId: '379694767475',
    projectId: 'ichibanauto-2f872',
    storageBucket: 'ichibanauto-2f872.appspot.com',
    iosBundleId: 'com.example.ichibanAuto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDB5d_6-VTmBPMlqeneO_wSBbp-GW4s0Eg',
    appId: '1:379694767475:ios:d7e7f4774b8e7be6dd3906',
    messagingSenderId: '379694767475',
    projectId: 'ichibanauto-2f872',
    storageBucket: 'ichibanauto-2f872.appspot.com',
    iosBundleId: 'com.example.ichibanAuto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDd2IHiApw7vrf5cIcJyqYQeWtmuQaH2p4',
    appId: '1:379694767475:web:ab7a64a12daa3980dd3906',
    messagingSenderId: '379694767475',
    projectId: 'ichibanauto-2f872',
    authDomain: 'ichibanauto-2f872.firebaseapp.com',
    storageBucket: 'ichibanauto-2f872.appspot.com',
    measurementId: 'G-SQ0HELWS2V',
  );
}
